// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// DBTX is the interface satisfied by both *pgxpool.Pool and *pgx.Tx.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

// Querier is the interface for all generated query methods.
type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	GetSessionByToken(ctx context.Context, refreshToken string) (Session, error)
	UpdateSessionRevoked(ctx context.Context, refreshToken string) error
	DeleteAllSessionsForUser(ctx context.Context, userID uuid.UUID) error
}

// Queries holds the database connection.
type Queries struct {
	db DBTX
}

// New creates a new Queries backed by the given connection.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// WithTx returns a new Queries bound to a transaction.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}

// NewPool is a convenience wrapper used in main.go.
func NewPool(pool *pgxpool.Pool) *Queries {
	return New(pool)
}
