// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

// User represents a row in the users table.
type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"-"` // Never expose hash in JSON responses
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// Session represents a row in the sessions table.
type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"-"` // Never expose token in JSON responses
	IsRevoked    bool      `json:"is_revoked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

// Vehicle represents a row in the vehicles table.
type Vehicle struct {
	ID           uuid.UUID `json:"id"`
	LicensePlate string    `json:"license_plate"`
	OwnerName    string    `json:"owner_name"`
	PhoneNumber  string    `json:"phone_number"`
	Make         *string   `json:"make,omitempty"`
	Model        *string   `json:"model,omitempty"`
	Year         *int32    `json:"year,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
}

// OilChangeRecord represents a row in the oil_change_records table.
type OilChangeRecord struct {
	ID                 uuid.UUID  `json:"id"`
	VehicleID          uuid.UUID  `json:"vehicle_id"`
	ServiceDate        time.Time  `json:"service_date"`
	CurrentMileage     int32      `json:"current_mileage"`
	NextServiceMileage *int32     `json:"next_service_mileage,omitempty"`
	NextServiceDate    *time.Time `json:"next_service_date,omitempty"`
	OilType            *string    `json:"oil_type,omitempty"`
	OilFilter          *string    `json:"oil_filter,omitempty"`
	NextOilFilter      *string    `json:"next_oil_filter,omitempty"`
	CreatedAt          time.Time  `json:"created_at"`
}
