// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	const query = `
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at, updated_at`

	row := q.db.QueryRow(ctx, query, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	const query = `
SELECT id, email, password_hash, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1`

	row := q.db.QueryRow(ctx, query, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	const query = `
SELECT id, email, password_hash, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1`

	row := q.db.QueryRow(ctx, query, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

type CreateSessionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	const query = `
INSERT INTO sessions (user_id, refresh_token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_token, is_revoked, expires_at, created_at`

	row := q.db.QueryRow(ctx, query, arg.UserID, arg.RefreshToken, arg.ExpiresAt)
	var i Session
	err := row.Scan(&i.ID, &i.UserID, &i.RefreshToken, &i.IsRevoked, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

func (q *Queries) GetSessionByToken(ctx context.Context, refreshToken string) (Session, error) {
	const query = `
SELECT id, user_id, refresh_token, is_revoked, expires_at, created_at
FROM sessions
WHERE refresh_token = $1
LIMIT 1`

	row := q.db.QueryRow(ctx, query, refreshToken)
	var i Session
	err := row.Scan(&i.ID, &i.UserID, &i.RefreshToken, &i.IsRevoked, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

func (q *Queries) UpdateSessionRevoked(ctx context.Context, refreshToken string) error {
	const query = `
UPDATE sessions
SET is_revoked = TRUE
WHERE refresh_token = $1`

	_, err := q.db.Exec(ctx, query, refreshToken)
	return err
}

func (q *Queries) DeleteAllSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	const query = `
DELETE FROM sessions
WHERE user_id = $1`

	_, err := q.db.Exec(ctx, query, userID)
	return err
}

// ── Vehicles ──────────────────────────────────────────────────────────────────

type CreateVehicleParams struct {
	LicensePlate string  `json:"license_plate"`
	OwnerName    string  `json:"owner_name"`
	PhoneNumber  string  `json:"phone_number"`
	Make         *string `json:"make"`
	Model        *string `json:"model"`
	Year         *int32  `json:"year"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	const query = `
INSERT INTO vehicles (license_plate, owner_name, phone_number, make, model, year)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, license_plate, owner_name, phone_number, make, model, year, created_at`

	row := q.db.QueryRow(ctx, query,
		arg.LicensePlate,
		arg.OwnerName,
		arg.PhoneNumber,
		arg.Make,
		arg.Model,
		arg.Year,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.LicensePlate,
		&i.OwnerName,
		&i.PhoneNumber,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) GetVehicleByID(ctx context.Context, id uuid.UUID) (Vehicle, error) {
	const query = `
SELECT id, license_plate, owner_name, phone_number, make, model, year, created_at
FROM vehicles
WHERE id = $1
LIMIT 1`

	row := q.db.QueryRow(ctx, query, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.LicensePlate,
		&i.OwnerName,
		&i.PhoneNumber,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) GetVehicleByLicensePlate(ctx context.Context, licensePlate string) (Vehicle, error) {
	const query = `
SELECT id, license_plate, owner_name, phone_number, make, model, year, created_at
FROM vehicles
WHERE license_plate = $1
LIMIT 1`

	row := q.db.QueryRow(ctx, query, licensePlate)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.LicensePlate,
		&i.OwnerName,
		&i.PhoneNumber,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) ListVehicles(ctx context.Context) ([]Vehicle, error) {
	const query = `
SELECT id, license_plate, owner_name, phone_number, make, model, year, created_at
FROM vehicles
ORDER BY created_at DESC`

	rows, err := q.db.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.LicensePlate,
			&i.OwnerName,
			&i.PhoneNumber,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type UpdateVehicleParams struct {
	ID           uuid.UUID `json:"id"`
	LicensePlate string    `json:"license_plate"`
	OwnerName    string    `json:"owner_name"`
	PhoneNumber  string    `json:"phone_number"`
	Make         *string   `json:"make"`
	Model        *string   `json:"model"`
	Year         *int32    `json:"year"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	const query = `
UPDATE vehicles
SET
    license_plate = $2,
    owner_name    = $3,
    phone_number  = $4,
    make          = $5,
    model         = $6,
    year          = $7
WHERE id = $1
RETURNING id, license_plate, owner_name, phone_number, make, model, year, created_at`

	row := q.db.QueryRow(ctx, query,
		arg.ID,
		arg.LicensePlate,
		arg.OwnerName,
		arg.PhoneNumber,
		arg.Make,
		arg.Model,
		arg.Year,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.LicensePlate,
		&i.OwnerName,
		&i.PhoneNumber,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) DeleteVehicle(ctx context.Context, id uuid.UUID) error {
	const query = `
DELETE FROM vehicles
WHERE id = $1`

	_, err := q.db.Exec(ctx, query, id)
	return err
}

// ── Oil Change Records ────────────────────────────────────────────────────────

type CreateOilChangeRecordParams struct {
	VehicleID          uuid.UUID  `json:"vehicle_id"`
	ServiceDate        time.Time  `json:"service_date"`
	CurrentMileage     int32      `json:"current_mileage"`
	NextServiceMileage *int32     `json:"next_service_mileage"`
	NextServiceDate    *time.Time `json:"next_service_date"`
	OilType            *string    `json:"oil_type"`
	OilFilter          *string    `json:"oil_filter"`
	NextOilFilter      *string    `json:"next_oil_filter"`
}

func (q *Queries) CreateOilChangeRecord(ctx context.Context, arg CreateOilChangeRecordParams) (OilChangeRecord, error) {
	const query = `
INSERT INTO oil_change_records (
    vehicle_id,
    service_date,
    current_mileage,
    next_service_mileage,
    next_service_date,
    oil_type,
    oil_filter,
    next_oil_filter
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, vehicle_id, service_date, current_mileage, next_service_mileage, next_service_date, oil_type, oil_filter, next_oil_filter, created_at`

	row := q.db.QueryRow(ctx, query,
		arg.VehicleID,
		arg.ServiceDate,
		arg.CurrentMileage,
		arg.NextServiceMileage,
		arg.NextServiceDate,
		arg.OilType,
		arg.OilFilter,
		arg.NextOilFilter,
	)
	var i OilChangeRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ServiceDate,
		&i.CurrentMileage,
		&i.NextServiceMileage,
		&i.NextServiceDate,
		&i.OilType,
		&i.OilFilter,
		&i.NextOilFilter,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) GetOilChangeRecordByID(ctx context.Context, id uuid.UUID) (OilChangeRecord, error) {
	const query = `
SELECT id, vehicle_id, service_date, current_mileage, next_service_mileage, next_service_date, oil_type, oil_filter, next_oil_filter, created_at
FROM oil_change_records
WHERE id = $1
LIMIT 1`

	row := q.db.QueryRow(ctx, query, id)
	var i OilChangeRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ServiceDate,
		&i.CurrentMileage,
		&i.NextServiceMileage,
		&i.NextServiceDate,
		&i.OilType,
		&i.OilFilter,
		&i.NextOilFilter,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) ListOilChangeRecordsByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]OilChangeRecord, error) {
	const query = `
SELECT id, vehicle_id, service_date, current_mileage, next_service_mileage, next_service_date, oil_type, oil_filter, next_oil_filter, created_at
FROM oil_change_records
WHERE vehicle_id = $1
ORDER BY service_date DESC`

	rows, err := q.db.Query(ctx, query, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []OilChangeRecord
	for rows.Next() {
		var i OilChangeRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.ServiceDate,
			&i.CurrentMileage,
			&i.NextServiceMileage,
			&i.NextServiceDate,
			&i.OilType,
			&i.OilFilter,
			&i.NextOilFilter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

func (q *Queries) GetLatestOilChangeRecord(ctx context.Context, vehicleID uuid.UUID) (OilChangeRecord, error) {
	const query = `
SELECT id, vehicle_id, service_date, current_mileage, next_service_mileage, next_service_date, oil_type, oil_filter, next_oil_filter, created_at
FROM oil_change_records
WHERE vehicle_id = $1
ORDER BY service_date DESC
LIMIT 1`

	row := q.db.QueryRow(ctx, query, vehicleID)
	var i OilChangeRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ServiceDate,
		&i.CurrentMileage,
		&i.NextServiceMileage,
		&i.NextServiceDate,
		&i.OilType,
		&i.OilFilter,
		&i.NextOilFilter,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) DeleteOilChangeRecord(ctx context.Context, id uuid.UUID) error {
	const query = `
DELETE FROM oil_change_records
WHERE id = $1`

	_, err := q.db.Exec(ctx, query, id)
	return err
}
