// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/lam-thinh/customer-oil-change-management"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/login": {
            "post": {
                "description": "Authenticate with email and password; returns an access token and sets a secure cookie containing a refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access token returned and cookie set",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed JSON",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revoke a refresh token from cookie. Requires a valid JWT access token in the Authorization header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "204": {
                        "description": "Logged out and cookie cleared"
                    },
                    "401": {
                        "description": "Not authenticated or token not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/refresh": {
            "post": {
                "description": "Exchange a valid refresh token cookie for a new access token (old refresh token is revoked)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh tokens",
                "responses": {
                    "200": {
                        "description": "New access token returned and cookie set",
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshResponse"
                        }
                    },
                    "401": {
                        "description": "Cookie not found, token revoked, or expired",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/register": {
            "post": {
                "description": "Create a new account with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created",
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed JSON",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email already registered",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/vehicles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all vehicles ordered by creation date descending",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "List vehicles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.VehicleResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a new vehicle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Create a vehicle",
                "parameters": [
                    {
                        "description": "Vehicle data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateVehicleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Vehicle created",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleResponse"
                        }
                    },
                    "400": {
                        "description": "Malformed JSON",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "License plate already registered",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vehicleID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a vehicle by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Get a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle UUID",
                        "name": "vehicleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vehicle found",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Vehicle not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update vehicle details by UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Update a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle UUID",
                        "name": "vehicleID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated vehicle data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVehicleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vehicle updated",
                        "schema": {
                            "$ref": "#/definitions/dto.VehicleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID or malformed JSON",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Vehicle not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "License plate already registered",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a vehicle and all associated oil change records by UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicles"
                ],
                "summary": "Delete a vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle UUID",
                        "name": "vehicleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Vehicle deleted"
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Vehicle not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vehicleID}/oil-changes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all oil change records for a vehicle, ordered by service date descending",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oil-changes"
                ],
                "summary": "List oil change records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle UUID",
                        "name": "vehicleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.OilChangeRecordResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Vehicle not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Log a new oil change service for a vehicle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oil-changes"
                ],
                "summary": "Create an oil change record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle UUID",
                        "name": "vehicleID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Oil change data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOilChangeRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Record created",
                        "schema": {
                            "$ref": "#/definitions/dto.OilChangeRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID or malformed JSON",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Vehicle not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vehicleID}/oil-changes/latest": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the most recent oil change record for a vehicle",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oil-changes"
                ],
                "summary": "Get latest oil change record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle UUID",
                        "name": "vehicleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Latest record",
                        "schema": {
                            "$ref": "#/definitions/dto.OilChangeRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Vehicle or record not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vehicleID}/oil-changes/{recordID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific oil change record by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oil-changes"
                ],
                "summary": "Get an oil change record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle UUID",
                        "name": "vehicleID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record UUID",
                        "name": "recordID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Record found",
                        "schema": {
                            "$ref": "#/definitions/dto.OilChangeRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Record not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a specific oil change record by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oil-changes"
                ],
                "summary": "Delete an oil change record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle UUID",
                        "name": "vehicleID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record UUID",
                        "name": "recordID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Record deleted"
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Record not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateOilChangeRecordRequest": {
            "type": "object",
            "required": [
                "current_mileage",
                "service_date"
            ],
            "properties": {
                "current_mileage": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 158397
                },
                "next_oil_filter": {
                    "type": "string",
                    "example": "1002"
                },
                "next_service_date": {
                    "type": "string",
                    "example": "2026-12-15T00:00:00Z"
                },
                "next_service_mileage": {
                    "type": "integer",
                    "example": 166397
                },
                "oil_filter": {
                    "type": "string",
                    "example": "1002"
                },
                "oil_type": {
                    "type": "string",
                    "example": "5W40"
                },
                "service_date": {
                    "type": "string",
                    "example": "2026-06-15T00:00:00Z"
                }
            }
        },
        "dto.CreateVehicleRequest": {
            "type": "object",
            "required": [
                "license_plate",
                "owner_name",
                "phone_number"
            ],
            "properties": {
                "license_plate": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "72A429.14"
                },
                "make": {
                    "type": "string",
                    "example": "Toyota"
                },
                "model": {
                    "type": "string",
                    "example": "Vios"
                },
                "owner_name": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Nguyễn Văn A"
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 20,
                    "example": "0981811837"
                },
                "year": {
                    "type": "integer",
                    "example": 2022
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid email or password"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "securePass123"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dto.OilChangeRecordResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-06-15T07:47:45Z"
                },
                "current_mileage": {
                    "type": "integer",
                    "example": 158397
                },
                "id": {
                    "type": "string",
                    "example": "49b586b2-4eda-436c-9b93-33d8306e18f0"
                },
                "next_oil_filter": {
                    "type": "string",
                    "example": "1002"
                },
                "next_service_date": {
                    "type": "string",
                    "example": "2026-12-15T00:00:00Z"
                },
                "next_service_mileage": {
                    "type": "integer",
                    "example": 166397
                },
                "oil_filter": {
                    "type": "string",
                    "example": "1002"
                },
                "oil_type": {
                    "type": "string",
                    "example": "5W40"
                },
                "service_date": {
                    "type": "string",
                    "example": "2026-06-15T00:00:00Z"
                },
                "vehicle_id": {
                    "type": "string",
                    "example": "b4925809-60f5-45f7-ad6e-1f0ca0922ea9"
                }
            }
        },
        "dto.RefreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "alice@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8,
                    "example": "securePass123"
                }
            }
        },
        "dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "alice@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dto.UpdateVehicleRequest": {
            "type": "object",
            "required": [
                "license_plate",
                "owner_name",
                "phone_number"
            ],
            "properties": {
                "license_plate": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "72A429.14"
                },
                "make": {
                    "type": "string",
                    "example": "Toyota"
                },
                "model": {
                    "type": "string",
                    "example": "Vios"
                },
                "owner_name": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Nguyễn Văn A"
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 20,
                    "example": "0981811837"
                },
                "year": {
                    "type": "integer",
                    "example": 2022
                }
            }
        },
        "dto.VehicleResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-06-29T07:45:51Z"
                },
                "id": {
                    "type": "string",
                    "example": "1b0a7a27-8b3b-475c-ac72-2ebca1a78d0a"
                },
                "license_plate": {
                    "type": "string",
                    "example": "72A429.14"
                },
                "make": {
                    "type": "string",
                    "example": "Toyota"
                },
                "model": {
                    "type": "string",
                    "example": "Vios"
                },
                "owner_name": {
                    "type": "string",
                    "example": "Nguyễn Văn A"
                },
                "phone_number": {
                    "type": "string",
                    "example": "0981811837"
                },
                "year": {
                    "type": "integer",
                    "example": 2022
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your JWT token in the format: **Bearer \u0026lt;token\u0026gt;**",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Customer Oil Change Management API",
	Description:      "A production-ready REST API for managing customer oil change records.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
